name: Support Request
description: Create a support ticket
labels: ['support']
body:
  - type: markdown
    attributes:
      value: |
        **Check for existing issues first**
        Before creating a new support request, please use the search function here in the Issues tracker to check if this problem or request has already been submitted.        
        Please also be sure to check the original [Nova-X Issues](https://github.com/darklinkpower/Nova-X) tracker. That theme has far more users, and your question may have already been answered there.
        
        If an issue exists, but has not been answered, **please do not create a new ticket**.
        Kindly keep in mind that *both* themes are single-developer projects.

        **Instructions**
        Please change the placeholder title automatically filled in the template and provide the information requested in the sections below. Fields marked with a * are required.
  - type: checkboxes
    attributes:
      label: Pre-Request Checklist
      description: Before submitting your report, please confirm the following
      options:
        - label: "I have serched existing issues (both open **and** closed, both here and at Nova-X) and confirm that this request has not been posted before."
          required: true
        - label: "This is not a feature request."
          required: true
  - type: textarea
    attributes:
      label: Support Request Description
      description: Provide a clear and concise description of the issue or support request, including any relevant details.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots, if applicable, to help explain the problem. This is especially useful for UI-related issues.
    validations:
      required: false